### ISSUE TITLE
version 20190521 from quicklisp will not load

### ISSUE THREAD

**Issue by beatastic** [bendudson/array-operations#28]
This is my output from a fresh install of quicklisp when I try to quickload :array-operations as of today.

* (ql:quickload :array-operations)
To load "array-operations":
  Load 1 ASDF system:
    asdf
  Install 4 Quicklisp releases:
    alexandria anaphora array-operations let-plus
; Fetching #<URL "http://beta.quicklisp.org/archive/anaphora/2018-02-28/anaphora-20180228-git.tgz">
; 6.01KB
==================================================
6,151 bytes in 0.00 seconds (0.00KB/sec)
; Fetching #<URL "http://beta.quicklisp.org/archive/alexandria/2018-12-10/alexandria-20181210-git.tgz">
; 50.00KB
==================================================
51,197 bytes in 0.00 seconds (49997.07KB/sec)
; Fetching #<URL "http://beta.quicklisp.org/archive/let-plus/2017-11-30/let-plus-20171130-git.tgz">
; 10.87KB
==================================================
11,126 bytes in 0.00 seconds (0.00KB/sec)
; Fetching #<URL "http://beta.quicklisp.org/archive/array-operations/2019-05-21/array-operations-20190521-git.tgz">
; 25.65KB
==================================================
26,268 bytes in 0.00 seconds (0.00KB/sec)
; Loading "array-operations"

debugger invoked on a QUICKLISP-CLIENT:SYSTEM-NOT-FOUND in thread
#<THREAD "main thread" RUNNING {100399C633}>:
  System "array-operations/all" not found

**Comment by bendudson** [comment]
Thanks for the report. What system is this on? `array-operations` is tested on Travis with fresh installs of SBCL and CCL and quicklisp. What version of ASDF are you using? (see https://common-lisp.net/project/asdf/asdf/How-do-I-detect-the-ASDF-version_003f.html)

**Comment by beatastic** [comment]
asdf 3.1.5
sbcl 1.3.1.debian (ubuntu OS)
unsure of quicklisp version # but updated this morning

**Comment by bendudson** [comment]
Travis runs SBCL 1.2.13 , ASDF 3.1.6
Just updated quicklisp, deleted and reloaded `array-operations` on SBCL 1.4.16, ASDF 3.3.1. 
Strange, maybe something else.

It looks like something is going wrong with the package inferred system; it should associate `array-operations/all` with `src/all.lisp`. Could you please try:

1. Just after https://github.com/bendudson/array-operations/blob/master/array-operations.asd#L8
Add the line 
```
:defsystem-depends-on (:asdf-package-system)
```
(following usage in https://davazp.net/2014/11/26/modern-library-with-asdf-and-package-inferred-system.html)

2. Loading the system with verbose output, to see any warnings:
```
(ql:quickload :array-operations :verbose t)
```
or
```
(asdf:load-system :array-operations)
```

**Comment by bendudson** [comment]
Ah wait a minute... The release notes for ASDF 3.1.6 include:
```
  * Fix component-finding in package-inferred-system.
```
https://allmychanges.com/p/common-lisp/asdf/

Would you mind updating ASDF and trying again?

**Comment by SubordinalBlue** [comment]
I thought we removed “anaphora” and “let-plus”.

Is he getting your array-operations, Ben, or the original?

**Comment by bendudson** [comment]
Unfortunately I had to reintroduce a dependence on `let-plus`, though not `anaphora`. It's possible/likely that `let-plus` depends on `anaphora`. The issue was that [lla](https://github.com/tpapp/lla) depends on a `let-plus` symbol being in `array-operations`.
See https://github.com/quicklisp/quicklisp-projects/issues/1683 for discussion.
The proper solution is maybe to patch `lla`, but that's currently unmaintained.

**Comment by beatastic** [comment]
Trying from my home system, I have ASDF 3.3.1 and it works perfectly.  I will try to update ASDF tomorrow on the other computer.  Thank you for the unprecedented amount of support.  It means a lot.

**Comment by bendudson** [comment]
Great! You're welcome, thanks for trying this out. I'll update the README with a note on ASDF version.
