### ISSUE TITLE
nested-loop documented but not exported

### ISSUE THREAD

**Issue by Symbolics** [bendudson/array-operations#31]
There's a note in `all.lisp`:

> ;; Note: array-operations/utilities *not* exported for external use.

**Comment by bendudson** [comment]
Good point. I guess no-one else had ever tried to use it :) Is this useful enough to export, or should the documentation for `nested-loop` just be moved to the end of the docs and marked as an internal utility?

**Comment by Symbolics** [comment]
I think it's useful enough to export

**Comment by Symbolics** [comment]
In `aops`, Tamas is using the `package-inferred-system` from ASDF and I'm not familiar enough with it to want to try to change it just yet.  The symbol is exported, but you have to explicitly `use` or import from the `array-operations/utilities` package. I'll document that fact and then close this.
