### ISSUE TITLE
Possible doc update

### ISSUE THREAD

**Issue by Symbolics** [bendudson/array-operations#32]
I'm making a lot of use of array-operations, and [polished the documentation a bit](https://lisp-stat.dev/docs/tasks/array-operations/). If this is useful, I can submit a pull request whenever I improve it.

**Comment by bendudson** [comment]
Hi @Symbolics thanks that looks nice! Documentation is always very welcome

**Comment by Symbolics** [comment]
Let me think about the best way to do this with minimal friction. With Papp's other libraries, I made the README describe logistics (see [numerical-utilities](https://github.com/Lisp-Stat/numerical-utilities) for an example) and linked to the website documentation. I supposed I could manually copy the website markdown into the README, but I would rather have a 'single source' if I can convince the doc generator and github repo to place nicely together. Alternatively, we could do the same and link to the website for docs, in which case it will always be up to date.

**Comment by Symbolics** [comment]
I haven't found a good way to keep the doc generator and repo in sync that doesn't require manual effort, so it's probably best to have a single source for the user manual; I'm currently maintaining that on the Lisp-Stat website.

Do you know if there is a way to exclude a single file from a git pull? The only thing that we might not want in this repo is the [README](https://github.com/Lisp-Stat/array-operations/blob/master/README.md) that refers to Lisp-Stat. If exclusion or manual-merge exclusion is too difficult, perhaps we can adjust the wording to suit both repos.

Also, some refactoring for consideration:

1. Put the API docs in a docs/ directory. As soon as version 4 of [declt](https://github.com/didierverna/declt) (should be soon) is released, I'm going to auto-generate docs for all the libraries I'm maintaining, then link to them from the repo main page (settings) for API level documentation.
2. Put a link to the lisp-stat [aops manual](https://lisp-stat.dev/docs/tasks/array-operations) in this repos README. I keep this user manual up to date, and have recently added documentation for several functions I discovered during my development with `aops`, and clarified descriptions of others (see [documentation change log](https://github.com/Lisp-Stat/documentation/commits/master) for details). This way users will always know where to go for the latest user manual.
3. Merge the [matrix package of numerical-utilities](https://github.com/Lisp-Stat/numerical-utilities/blob/master/src/matrix.lisp) into `aops`. I think they belong here more than they do in `numerical-utilities`.  I've taken over maintenance of several of Tamas's libraries, including `numerical-utilities` and replacing Tamas' Quicklisp libraries with the ones from Lisp-Stat, so it will be easy to do this (well, at least from a coordination standpoint).

Finally, I recently added a `map-array` that maps a function over each element of an array ([each](https://lisp-stat.dev/docs/tasks/array-operations/#each) does not do this and should probably be renamed). Hard to believe there wasn't one in all the functionality of `aops`, but there you go; I hope I didn't just miss it, but if I did it underscores the need for improved documentation. I'd like to get `map-array` into the main `aops` distribution, as I use it in Lisp-Stat and Quicklisp is complaining about its absence.

Perhaps we could start by doing a merge request from the Lisp-Stat repo and discuss the issues as they come up?

**Comment by bendudson** [comment]
Hopefully this issue is now resolved, thanks @Symbolics!
