### ISSUE TITLE
Is there a function for rotating an array by 90/180/270 degrees?

### ISSUE THREAD

**Issue by phoe** [bendudson/array-operations#33]
Is there any kind of operator that I can use to destructively/nondestructively "rotate" a 2D array by 90/180/270 degrees? If not, would it be permissible to add one?

Example behavior that I am thinking of:

```lisp
;; 90 degrees
#2A((1 0 0)    #2A((3 2 1)
    (2 0 0)  →     (0 0 0)
    (3 0 0))       (0 0 0))

;; 180 degrees
#2A((1 0 0)    #2A((0 0 3)
    (2 0 0)  →     (0 0 2)
    (3 0 0))       (0 0 1))

;; 270 degrees
#2A((1 0 0)    #2A((0 0 0)
    (2 0 0)  →     (0 0 0)
    (3 0 0))       (1 2 3))
```

**Comment by Symbolics** [comment]
There isn't anything to do this at the moment. You might be able to do what you want with [permute](https://lisp-stat.dev/docs/tasks/array-operations/#permute) or `stack`.

A couple of questions:

1. What is the use case? I don't think I've encountered a need to rotate a matrix, at least in the domains I work in.
2. What happens in the case of arrays of rank > 2?

**Comment by phoe** [comment]
1) I have an ARGB image encoded as a 2D array of `(unsigned-byte 32)` and dimensions `(m n)`.
I want to rotate it by 90°, and the simplest way of doing that is by creating an array with flipped dimensions, `(n m)`, and copying each row of the old array into each column of the new array.
I can do it on my own, I am simply wondering if this function belongs as a utility in `aops`.
2) You obviously need to specify an axis of rotation, because e.g. a 3D array can have three axes of rotation.
I think this can be declared via specifying the array dimensions that should be switched around, for example `(a b c)` → `(a c b)`, or just `(1 2)` because the 0th rank stays constant.

**Comment by Symbolics** [comment]
I think a well thought out contribution along these lines to be worthwhile addition. If Ben doesn't want it here, I'll take it in [my fork](https://github.com/Lisp-Stat/array-operations).

**Comment by phoe** [comment]
Initial implementation done and ready for review in #34.
